"""
Django settings for online_garage project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# from decouple import config
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-)hr5(&m$p!p2z*d!zkd3!me7712vre%2ng%465i3536*4^2uzl'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'corsheaders',
    # Your local app
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'online_garage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_garage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# # --- Database Configuration (Robust for Testing) ---
# # First, parse the database URL from the .env file into a dictionary
# db_config = env.db_url(
#     'DATABASE_URL',
#     engine='django.contrib.gis.db.backends.postgis'
# )

# # Now, manually add the TEST settings to this configuration dictionary
# db_config['TEST'] = {
#     'NAME': db_config.get('NAME'),  # Use the same name, Django will prefix it with 'test_'
#     'TEMPLATE': 'template_postgis', # Tells Django to copy our pre-configured template
# }

# # Finally, assign the fully constructed dictionary to the DATABASES setting
# DATABASES = {
#     'default': db_config
# }

DATABASES = {
    # Parse DB url automatically
     'default': env.db_url(
         'DATABASE_URL',
         engine='django.contrib.gis.db.backends.postgis'  # Use PostGIS for GIS support
         )
         
}

#Extension template database
DATABASES ['default']['TEST'] = {
    'TEMPLATE': 'template_postgis',  # Use a temporary database for tests
    }# DATABASES ['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = [env('FRONTEND_URL')]

# DRF and Auth Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',)
}

#All auth settings
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default backend ie username/password login
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth  backend ie email/password login
)


# Authentication settings

# REST_AUTH = {
#     'LOGIN_SERIALIZER': 'api.serializers.CustomLoginSerializer',  # Use our custom login serializer
# }

# Allauth settings
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # We don't use a username
ACCOUNT_AUTHENTICATION_METHOD = 'email'   # Login with email
ACCOUNT_EMAIL_REQUIRED = True             # Email is required
ACCOUNT_UNIQUE_EMAIL = True               # Each email must be unique
ACCOUNT_USERNAME_REQUIRED = False         # Username is not required
ACCOUNT_EMAIL_VERIFICATION = 'optional'   # Or 'mandatory' or 'none'

# ACCOUNT_AUTHENTICATION_METHOD = None
# ACCOUNT_LOGIN_METHOD = 'email'
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# SITE_ID = 1  # Required for allauth to work properly
# ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Or 'mandatory' or 'none'
SITE_ID = 1
# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # For development
